# Generated by Django 4.1.4 on 2023-03-27 13:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('htype', models.CharField(choices=[('5star', '5star'), ('4star', '4star'), ('Lodge', 'Lodge'), ('Doormetry', 'Doormetry')], default='5star', max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveIntegerField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomstatus', models.CharField(choices=[('available', 'available'), ('not available', 'not available')], default='available', max_length=200)),
                ('rtype', models.CharField(choices=[('classic', 'classic'), ('premium', 'premium'), ('dulex', 'dulex')], default='classic', max_length=200)),
                ('capacity', models.CharField(choices=[('2-double bed', '2-double bed'), ('3-king size', '3-king size'), ('1-single bed', '1-single bed')], default='2-double bed', max_length=200)),
                ('roomimage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.CharField(max_length=260)),
                ('price', models.PositiveIntegerField()),
                ('doornum', models.IntegerField()),
                ('fmenu', models.CharField(choices=[('breakfast included', 'breakfast included'), ('breakfast not-included', 'breakfast not-included'), ('breakfast & dinner included', 'breakfast & dinner included'), ('breakfast & dinner not-included', 'breakfast & dinner not-included')], default='breakfast included', max_length=200)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=260)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileno', models.PositiveIntegerField(unique=True)),
                ('owneraddress', models.CharField(max_length=200)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.place'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
